
world_frame: map

# sensors

amcl: amcl_pose
amcl_config: [true,  true,  true,
              true, true, true,
              false,  false, false,
              false, false, false,
              false, false, false]

imu: imu_data
imu_config: [false,  false,  false,
              true, true, true,
              false,  false, false,
              false, false, false,
              true, true, true]

debug: true
debug_out_file: ~/debug.txt
