obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.4445, 0.4445], [0.4445, -0.4445], [-0.4445, -0.4445], [-0.4445, 0.4445]]

inflation_radius: 0.7

observation_sources: front_laser

front_laser: {sensor_frame: /lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

# point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}